a_tensor_initialization.py
--------------------------

### 텐서 초기화
1. torch.Tensor 클래스: PyTorch의 기본 텐서 타입 클래스. torch.FloatTensor의 별칭이며 이름대로 텐서를 float32 데이터 타입으로 생성한다. 이 데이터 타입은 고정이므로 클래스를 사용할 때 dtype 인자를 사용할 수 없다. 현재는 잘 사용하지 않는 생성 방식.
* 예: torch.Tensor([1, 2, 3])으로 만들고 출력하면 [1., 2., 3.]으로 나온다.
  
2. torch.tensor 함수: 따로 dtype 인자를 사용하지 않으면 입력된 데이터의 타입으로 자동으로 설정된다.
* 예: torch.tensor([1, 2, 3], dtype=torch.int64), torch.Tensor([1, 2, 3]).to(torch.int64), torch.LongTensor([1, 2, 3]). 모두 [1, 2, 3]으로 나온다.

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
# torch.tensor function: 모든 텐서는 device, dtype, shape, requires_grad 속성이 있다.
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # 텐서의 데이터 타입 (float32, int64 등)
print(t2.device)  # 텐서가 저장된 장치 (CPU, GPU 등)
print(t2.requires_grad)  # 텐서의 자동 미분 허용 여부. 텐서는 기본값 None인 기울기 속성을 가지고 있고 역전파 과정을 통해 기울기가 계산된다.
                         # requires_grad를 True로 설정해야 역전파 과정해서 계산된 기울기값이 텐서의 기울기 속성에 할당된다.
print(t2.size())
print(t2.shape)  # 텐서의 크기=차원 구조

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # PyTorch 텐서는 모든 차원에서 같은 길이를 가져야한다.
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
# a11은 4×1×2×(마지막 차원) 구조인데, 마지막 차원중 하나는 길이가 3, 다른 하나는 길이가 2라서 서로 다르다.

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

b_tensor_initializatioin_copy.py
--------------------------------

In [5]:
import torch
import numpy as np
# 데이터로부터 직접적으로 텐서 초기화

In [6]:
# torch.Tensor와 torch.tensor는 언제나 주어진 데이터를 복사해서 텐서를 만든다.
# torch.Tensor: 주어진 데이터를 float32로 복사해서 텐서를 만든다('.'이 붙는 이유는 그 때문).
# 셋 모두 리스트와 numpy에 사용할 수 있다.
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

# torch.tensor: 주어진 데이터를 그대로 복사해서 텐서를 만든다.
l2 = [1, 2, 3]
t2 = torch.tensor(l2)

# torch.as_tensor: 주어진 데이터를 '복사하지 않고' 그대로 참조한다(원본 데이터가 바뀌면 텐서도 같이 바뀜).
# 다만 단순 리스트는 참조가 되지 않는다. l3[0]=100이 적용되지 않는 이유도 그 때문.
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [7]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6) # torch.as_tensor가 numpy 배열인 l6를 복제하지 않고 그대로 참조하기 때문에 l6[0]=100이 적용된다.
          # numpy 배열이 복제되길 원치 않는다면 torch.as_tensor()를 사용하면 된다.

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


c_tensor_initializatioin_constant_values.py
-----------------------------

In [8]:
import torch
# 상수로 텐서 초기화

In [9]:
# torch.ones(*size): 1로 채워진 *size 크기의 텐서 생성
t1 = torch.ones(size=(5,))  # or torch.ones(5)

# torch.ones_like(input_tensor): input_tensor와 같은 shape를 가진 1로 채운 텐서 생성
t1_like = torch.ones_like(input=t1)

print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

# 추가 코드
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
tx = torch.ones_like(input=x)
print(tx)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [10]:
# torch.zeros(*size): 0으로 채워진 *size 크기의 텐서 생성
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)

# torch.zeros_like(input_tensor): input_tensor와 같은 shape를 가진 0으로 채운 텐서 생성
t2_like = torch.zeros_like(input=t2)

print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

# 추가 코드
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
tx = torch.zeros_like(input=x)
print(tx)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [11]:
# torch.empty(*size): '초기화되지 않은 데이터(무작위값)'로 채워진 *size 크기의 텐서 생성
t3 = torch.empty(size=(4,))  # or torch.zeros(4)

# torch.empty_like(input_tensor): input_tensor와 같은 shape를 가진 초기화되지 않은 데이터로 채워진 텐서 생성.
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

# 추가 코드
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
tx = torch.empty_like(input=x)
print(tx)

tensor([2.1698e-19, 7.2587e-43, 3.0000e+00, 0.0000e+00])
tensor([0.0000, 4.4766, 0.0000, 0.0000])
tensor([[2225338451824,             0,             0],
        [            0,             0,             0]])


In [12]:
# torch.eye(n): 단위행렬(대각선만 1이고 나머지는 0인 n×n 텐서) 생성
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


d_tensor_initialization_random_values.py
----------------------------------------

In [13]:
import torch
# 무작위 값으로 텐서 초기화

In [14]:
# torch.randint(low=0, high, size, ...): low이상 high미만으로 균등하게 분포된 정수 난수로 텐서를 채움.
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[10, 16]])


In [15]:
# torch.rand(*size, ...): 0이상 1미만으로 균등하게 분포된 난수로 텐서를 채움.
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.2013, 0.4258, 0.1916]])


In [16]:
# torch.randn(*size, ...): 평균이 0이고 분산이 1인 표준정규분포에서 뽑은 float 난수로 텐서를 채움.
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.3902,  0.5602,  0.3644]])


In [17]:
# torch.normal(mean, std, size, ...): 평균(mean)과 표준편차(std)가 주어진 정규분포에서 뽑은 float 난수로 텐서를 채움.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[10.6666,  8.8450],
        [ 8.0792, 10.6487],
        [11.8867,  9.9282]])


In [18]:
# torch.linspace(start, end, steps, …): start부터 end까지 균등 간격으로 나눈 steps개의 값들로 채워진 1차원 텐서를 반환.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 추가 코드
t5x = torch.linspace(start=0, end=1, steps=5)
print(t5x)

tensor([0.0000, 2.5000, 5.0000])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [19]:
# torch.arange(start=0, end, steps=1,…): start이상 end 미만까지 steps 간격으로 생성된 값들로 채워진 1차원 텐서를 반환.
t6 = torch.arange(5)
print(t6)

# 추가 코드
t6x = torch.arange(1, 14, 3)
print(t6x)

tensor([0, 1, 2, 3, 4])
tensor([ 1,  4,  7, 10, 13])


#### Random seed(무작위 seed)

In [21]:
# torch.manual_seed(seed): 난수 생성기의 seed를 고정된 값으로 설정함으로써 사용자가 torch.rand(2) 예제를 호출했을 때, 결과가 재현가능해진다. 
torch.manual_seed(1729) # seed를 1729로 고정
random1 = torch.rand(2, 3) # 2×3 shape의 첫 번째 무작위 텐서 생성
print(random1)

random2 = torch.rand(2, 3) # 두 번째 무작위 텐서 생성
print(random2)

print()

torch.manual_seed(1729) # seed를 위와 똑같이 맞춰주면
random3 = torch.rand(2, 3) # random3는 random1과
print(random3)

random4 = torch.rand(2, 3) # random4는 random2와
print(random4) # 똑같은 결과를 출력한다.
# 실험 과정에서 무작위성 때문에 결과가 매번 달라지지 않도록, 한 번 얻은 랜덤 값을 계속 재현해 쓰는 데 사용한다.

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


e_tensor_type_conversion.py
---------------------------

In [22]:
import torch
# 텐서 타입 변환

In [23]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. # 생성된 2×3 텐서의 모든 원소 값에 20을 곱함.
print(c)

d = c.to(torch.int32) # c의 float64값을 int32로 변환=소수점 이하를 버림.
print(d)

# double은 float64, short는 int64의 약칭.
# 아래 4가지 표현(double/short, double()/short(), to(torch.double)/to(torch.short), type(torch.double)/type(torch.short))은 모두 같은 결과임.
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
# 추가 코드
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
# 추가 코드
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(torch.short)
# 추가 코드
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype) # float64인 double_f와 int16인 short_g의 곱셈은 int16을 float64로 변환하여 수행.


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[18,  7, 19],
        [10,  2, 19]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64


f_tensor_operations.py
----------------------

In [24]:
import torch

In [25]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))

t3 = torch.add(t1, t2) # t1 + t2
t4 = t1 + t2

print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [26]:
t5 = torch.sub(t1, t2) # t1 - t2
t6 = t1 - t2
print(t5)
print(t6)

# 추가 코드
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[6, 5, 4], [3, 2, 1]])
print(torch.sub(x, y))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-5, -3, -1],
        [ 1,  3,  5]])


In [27]:
t7 = torch.mul(t1, t2) # t1 * t2
t8 = t1 * t2
print(t7)
print(t8)

# 추가 코드
print(torch.mul(x, y))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 6, 10, 12],
        [12, 10,  6]])


In [28]:
t9 = torch.div(t1, t2) # t1 / t2
t10 = t1 / t2
print(t9)
print(t10)

# 추가 코드
print(torch.div(x, y))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1667, 0.4000, 0.7500],
        [1.3333, 2.5000, 6.0000]])


g_tensor_operations_mm.py
-------------------------

In [29]:
import torch
# dot, mm, bmm 모두 broadcasting 지원 없음

In [30]:
# torch.dot(input, other): 2개의 1차원 텐서의 내적 연산 수행. 두 텐서의 길이는 같아야 함.
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

# torch.mm(input, other): broadcasting 없이 2차원 행렬 곱셈 연산 수행.
# (n×m)×(m×p)→(n×p)
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

# torch.bmm(input, other): broadcasting 없이 배치 행렬 곱셈 연산 수행.
# (b×n×m)×(b×m×p)→(b×n×p)
# batch는 한 번에 처리하는 데이터 묶음을 의미하며, batch 차원은 행렬의 첫 번째 차원을 의미함.
t5 = torch.randn(10, 3, 4) # batch=10, 3×4
t6 = torch.randn(10, 4, 5) # batch=10, 4×5
t7 = torch.bmm(t5, t6)
print(t7.size())

# 추가 코드
# torch.mul(input, other): broadcasting을 지원하는 원소별 곱셈 연산
t8 = torch.mul(
    torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])
)
print(t8, t8.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])
tensor([[ 5, 12],
        [21, 32]]) torch.Size([2, 2])


h_tensor_operations_matmul.py
-----------------------------

In [31]:
import torch

In [32]:
# torch.matmul(Tensor, Tensor): broadcasting을 지원하는 다양한 텐서 곱 연산.
# 입력 텐서의 shape에 따라 다른 모드를 사용한다.
# 내적, 행렬, 배치 행렬 곱셈 연산 모두 지원

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4) # broadcasting으로 4짜리 행렬이 4×1 행렬로 전환되어 연산 실행.
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4) # braodcasting으로 4짜리 행렬이 10×4×1 행렬로 전환되어 연산 실행.
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5) # broadcasting으로 4×5 행렬이 10×4×5 행렬로 전환되어 연산 실행.
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


i_tensor_broadcasting.py
------------------------

In [33]:
import torch
# broadcasting: 텐서 간 연산 시 작은 텐서가 큰 텐서와 호환되는 shape이 되도록 broadcast되어 두 텐서 간 원소별 연산이 수행될 수 있도록 해준다.
# broadcasting 시 더 작은 배열이 더 더 큰 배열에 맞게 새로운 축이 추가되고, 변환된 배열에 맞게 데이터가 적절히 더해진다.

In [34]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0 # 스칼라 텐서가 [2.0, 2.0, 2.0]로 변환됨.
print(t1 * t2)

tensor([2., 4., 6.])


In [35]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5]) # shape이 2인 행렬이 broadcasting으로 3×2로 변환됨.
                          # ([4, 5], [4, 5], [4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [36]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [37]:
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size()) # 텐서의 값에만 적용되는 함수는 텐서의 shape에는 영향 없음.

# 추가 코드
print(t6)
print(normalize(t6))

torch.Size([3, 28, 28])
tensor([[[-0.3970,  0.7016,  0.9221,  ..., -0.1537,  0.7817,  0.7875],
         [ 1.8459, -2.5061,  0.6333,  ...,  2.1567,  0.5248,  0.7586],
         [ 0.1338, -0.6398, -0.3082,  ..., -0.3877, -2.3846,  1.2006],
         ...,
         [ 1.2316,  0.9079,  0.0856,  ...,  1.2696, -0.4395,  0.4958],
         [-0.1648,  0.4693, -0.6671,  ..., -0.2604, -0.9668,  0.4738],
         [-0.2336, -1.1732,  1.6757,  ...,  0.0724,  0.4495,  1.7352]],

        [[ 1.2012,  0.9665,  3.2020,  ..., -0.5740,  0.0999, -1.3696],
         [-0.3583,  0.8137,  0.1895,  ...,  0.5906,  0.7782, -1.1740],
         [ 0.0834,  1.0572, -0.0782,  ...,  0.2611, -0.9627, -0.3044],
         ...,
         [-0.9768,  0.6411, -0.7873,  ..., -0.7498,  0.6062, -1.1202],
         [ 1.1020,  0.9198, -0.3662,  ...,  1.2218,  0.1075, -0.9857],
         [ 1.7829, -0.2359, -0.3692,  ..., -0.6503,  1.3735, -0.9018]],

        [[ 0.6798, -0.0925,  0.9455,  ...,  0.1497,  0.5510, -0.8752],
         [-0.3503, -0

### ※ 브로드캐스팅 규칙
각 차원은 뒤에서부터 앞으로 가면서 비교한다.
1. 각 차원은 같거나
2. 각 차원 중 하나는 1이어야 한다.
3. 두 텐서 중 하나는 차원이 존재하지 않아야 한다.
---------------------------------------
#### 예시 문제
두 텐서 a=torch.tensor(5, 1, 3, 1), b=torch.tensor(3, 3, 1)이 있다. a+b 연산을 하고자 할 때
    
    ① 우측 정렬을 시켜준 후 뒤에서부터 앞으로 비교한다.
    first←last
    5 1 3 1
      3 3 1
    두 텐서를 비교했을 때 3번 차원(1과 1)은 같으므로 1번 규칙을 충족한다.
    다만 0번(5,  )과 1번(1, 3) 차원은 서로 다르다.
    이 때 두번째 규칙으로 넘어간다.
    ② 1번 차원(1과 3) 중 a가 1이므로 2번 규칙을 만족한다.
    ③ 0번 차원(5와  ) 중 b쪽이 차원이 존재하지 않으므로 3번 규칙을 만족한다.
    조건을 만족하므로 a와 b는 브로드캐스팅이 시행된다.

이렇게 브로드캐스팅이 지원되면서 a+b 연산이 시행되면, 결과값의 *shape*은 각 축을 비교해서 더 큰 쪽으로 나오게 된다.
a+b=(5, 1, 3, 1)+(3, 3, 1)=c=(5, 3, 3, 1)
=> c의 shape은 (5, 3, 3, 1)

In [38]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [39]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [40]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1
# a: 5 2 4 1
# b:   3 1 1
# 0번 차원: 5와    => 3번 규칙 만족
# 1번 차원: 2와 3 => 값이 같거나 어느 한쪽이 1도 아니고 둘 다 차원이 존재하므로 1, 2, 3번 규칙 모두 불만족
# 2번 차원: 4와 1 => b의 차원이 1이므로 2번 규칙 만족
# 3번 차원: 1과 1 => 값이 같으므로 1번 규칙 만족
# => 1번 차원이 규칙을 모두 불만족하므로 브로드캐스팅 불가.

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [41]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

# pow(x, n): 행렬 x의 각 원소를 n만큼 제곱
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp) # 각 원소별로 제곱(1^1, 2^2, 3^3, 4^4)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

# 추가 코드
exp2 = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a2 = torch.arange(3., 7.)  # tensor([ 3.,  4.,  5.,  6.])
t29 = torch.pow(a2, exp2) # 각 원소별로 제곱(1^3, 2^4, 3^5, 4^6)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])
tensor([   3.,   16.,  125., 1296.])


j_tensor_indexing_slicing.py
----------------------------

### 텐서 인덱싱 & 슬라이싱
- 텐서에서 특정 원소나 구간(슬라이스)을 접근하거나 가져오는 것
- 일반 기법
  * 기본 인덱싱: 각 차원에 대한 인덱스를 지정하여 텐서의 개별 원소에 접근
  * 슬라이싱: 각 차원에서 구간을 지정하여 그 구간만큼 부분 텐서를 추출

In [42]:
import torch

In [43]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # 1번 행 전체

print(x[:, 1])  # 모든 행의 1번 열
print(x[1, 2])  # 1행 2열의 원소
print(x[:, -1])  # 모든 행의 마지막 열

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [44]:
print(x[1:])  # 1행부터 끝까지
print(x[1:, 3:])  # 1행부터 마지막 행 중에서 마지막과 그 직전 열

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [45]:
y = torch.zeros((6, 6)) # 원소가 모두 0인 6×6 텐서를 만들고
y[1:4, 2] = 1 # 1번 행부터 3번 행까지 중 2열에 1을 삽입
print(y)

print(y[1:4, 1:4]) # 1~3번행, 1~3번열의 부분 텐서 추출

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2]) # 0~1번 행
print(z[1:, 1:3]) # 1행부터 끝행까지 1~2번열 출력
print(z[:, 1:]) # 모든 행의 1열부터 끝번열 출력

z[1:, 1:3] = 0 # 1행부터 끝행까지 1~2번열에 0 삽입
print(z)

In [46]:
# 추가 코드
# 고급 인덱싱: 몇몇 라이브러리들은 boolean mask나 인덱싱 배열을 하용하여 특정 조건에 맞는 원소를 선택하는 더 진보된 인덱싱 방법을 지원한다.
x = torch.arange(10)
print(x[x > 5]) # boolean mask 사용

y = torch.tensor([[10, 20, 30], [40, 50, 60]])
idx = torch.tensor([0, 2])
print(y[0, idx]) # 행렬 y의 0번행에서 0, 2번열만 추출

tensor([6, 7, 8, 9])
tensor([10, 30])


k_tensor_reshaping.py
---------------------

### 텐서 Reshaping
- torch.view(input, *shape) & torch.reshape(input, shape): 텐서의 데이터를 변경하지 않고 shape을 바꾸는 함수. 반환된 텐서는 원래 텐서와 동일한 메모리(데이터)를 공유함.
- torch.view()는 연속적인 텐서에서만 동작함.
- torch.reshape()는 비연속적 텐서에 대해서는 복사본을 반환할 수도 있음.

- torch.squeeze(): 크기가 1이거나, 크기가 1인 지정한 차원을 제거함.
- unsqueeze와 달리 () 안에 숫자를 꼭 넣지 않아도 되지만, 이 경우 크기가 1인 모든 차원을 제거함. 반대로 shape이 (2, 3)인 텐서 등 크기가 1인 차원이 없는 텐서에 squeeze를 사용하면 변화 없음.
- torch.flatten(input, start_dim=0, end_dim=-1): 텐서를 1차원 텐서로 펼침(flatten). start_dim과 end_dim을 지정하면 해당 구간의 차원만 펼쳐줌. 즉, shape를 start_dim×end_dim으로 만들어줌.
- torch.permute(input, dims)&torch.transpose(input, dim0, dim1): 원래 텐서의 데이터를 복사하지 않고, 차원의 순서를 바꾼 뷰를 반환.
- torch.permute(input, dims): 텐서의 모든 차원의 순서를 원하는 대로 재배치 가능. dims는 튜플/리스트 형태로 전체 차원의 새로운 순서를 지정.
- torch.transpose(input, dims0, dims1): 지정한 두 개의 차원만 서로 맞바꿈. 2차원 행렬에서는 행렬의 전치와 같은 동작을 수행.
- torch.t(): 2차원 텐서만 입력으로 받아 0번째 차원과 1번째 차원을 전치시킴. 행렬 전치 연산 전용 단축 함수로 쓰임.

In [47]:
import torch
# Tensor Reshaping

In [48]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [50]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# torch.unsqueeze(): 텐서에 새로운 차원을 지정한 위치에 추가
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [51]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15) # shape는 2×2×2=8

t17 = torch.flatten(t15, start_dim=1) # shape는 2×(2×2)→2×4

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [52]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


l_tensor_concat.py
------------------

### 텐서 스택킹
- 여러 개의 텐서를 지정한 차원(dim)을 따라 연결시킨 새로운 텐서를 반환하는 기법.
- 연결은 여러 개의 텐서의 지정된 차원'만'을 더하는 식으로 이루어짐.
- torch.concat()은 torch.cat()의 별칭임.
- torch.stack(tensors, dim=0): 여러 텐서를 새로운 차원으로 쌓아서(stack) 하나의 텐서로 병합한다. 병합된 텐서는 지정된 차원의 추가로 원래 텐서보다 1차원 더 많으며, 사용 시 모든 텐서의 크기가 동일해야 한다.

In [53]:
import torch

In [54]:
# 주의: torch.zeros는 데이터가 아닌 size가 인자로 들어감
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [55]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [56]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [57]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [58]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


m_tensor_stacking.py
--------------------

In [59]:
import torch

In [60]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2×3 텐서
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]]) # 2×3 텐서

# 아래의 stack과 cat은 출력 결과가 같다.
t3 = torch.stack([t1, t2], dim=0) # t1과 t2에 0번 차원을 추가 후 병합.
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [61]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


n_tensor_vstack_hstack.py
-------------------------

In [62]:
import torch

In [63]:
# torch.vstack(tensors): 텐서를 수직=세로 방향=행 기준으로 쌓아 병합. 모든 텐서의 '열' 수가 동일해야 함.
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [64]:
# torch.hstack(tensors): 텐서를 수평으로=가로 방향=열 기준으로 쌓아 병합. 모든 텐서의 '행' 수가 동일해야 함.
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기
 PyTorch 라이브러리와 Tensor 자료구조의 문법, Jupyter Notebook 플랫폼과 마크다운 문법까지 딥러닝 공부에 필요한 여러 프로그램들을 실습해볼 수 있는 유익한 과제였습니다. 오프라인 강의로 처음 배울 때와 온라인 강의로 보고듣기만 할 때는 이해가 잘 되지 않던 문법들도 차근차근 실습해보고 제가 이해한 내용을 주석 등 글로 정리하면서 훨씬 수월하게 익힐 수 있었습니다.